name: CI

on: [ push, pull_request ]

jobs:
  php:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: my-secret-pw
          POSTGRES_DB: criti-pixel
        options: >-
          --health-cmd "pg_isready -U root" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --no-cache

      - name: Compile Sass
        run: php bin/console sass:build

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Prepare Database
        run: |
          php bin/console make:migration
          php bin/console doctrine:database:drop --if-exists --env=test --force
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
          php bin/console doctrine:fixtures:load --no-interaction --env=test

      - name: Export Database
        run: pg_dump -U root --host=127.0.0.1 --port=5432 criti-pixel > database_dump.sql

      - name: Upload Database Dump
        uses: actions/upload-artifact@v4
        with:
          name: database-dump
          path: database_dump.sql

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist
